# spring.application.name=security-demo
spring:
  application:
    name: security-demo

  datasource:
    url: jdbc:mysql://localhost:32768/testerDB
    username: root
    password: adarshgs
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    user:
      name: root
      password: root

myapp:
  secret-key: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  access-maxage: 60
  refresh-maxage: 90
